package com.ericsson.tm.cbio.rateplansread;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.12-soa-02
 * Tue Jan 26 11:29:24 CST 2016
 * Generated source version: 2.2.12-soa-02
 * 
 */
 
@WebService(targetNamespace = "http://ericsson.com/services/ws_CIL_5", name = "RateplansReadService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RateplansReadService {

    @WebResult(name = "rateplansReadResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_5/rateplansread", partName = "rateplansReadResponse")
    @WebMethod
    public RateplansReadResponse rateplansRead(
        @WebParam(partName = "rateplansReadRequest", name = "rateplansReadRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_5/rateplansread")
        RateplansReadRequest rateplansReadRequest
    );
}
