package com.ericsson.tm.cbio.paymentarrangementsread;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.12-soa-02
 * Tue Jan 26 11:28:42 CST 2016
 * Generated source version: 2.2.12-soa-02
 * 
 */
 
@WebService(targetNamespace = "http://ericsson.com/services/ws_CIL_5", name = "PaymentArrangementsReadService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PaymentArrangementsReadService {

    @WebResult(name = "paymentArrangementsReadResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_5/paymentarrangementsread", partName = "paymentArrangementsReadResponse")
    @WebMethod
    public PaymentArrangementsReadResponse paymentArrangementsRead(
        @WebParam(partName = "paymentArrangementsReadRequest", name = "paymentArrangementsReadRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_5/paymentarrangementsread")
        PaymentArrangementsReadRequest paymentArrangementsReadRequest
    );
}
