package com.ericsson.tm.cbio.servicesread;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.12-soa-02
 * Tue Jan 26 11:31:07 CST 2016
 * Generated source version: 2.2.12-soa-02
 * 
 */
 
@WebService(targetNamespace = "http://ericsson.com/services/ws_CIL_5", name = "ServicesReadService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServicesReadService {

    @WebResult(name = "servicesReadResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_5/servicesread", partName = "servicesReadResponse")
    @WebMethod
    public ServicesReadResponse servicesRead(
        @WebParam(partName = "servicesReadRequest", name = "servicesReadRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_5/servicesread")
        ServicesReadRequest servicesReadRequest
    );
}
