
/*
 * 
 */

package com.ericsson.services.ws_cil_5;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.12-soa-02
 * Wed Jan 27 04:38:43 CST 2016
 * Generated source version: 2.2.12-soa-02
 * 
 */


@WebServiceClient(name = "SoaService", 
                  wsdlLocation = "file:/C:/Env/TestMerge1/WebContent/wsdl/ws_CIL_5_SoaService.wsdl",
                  targetNamespace = "http://ericsson.com/services/ws_CIL_5") 
public class SoaService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ericsson.com/services/ws_CIL_5", "SoaService");
    public final static QName SoaService = new QName("http://ericsson.com/services/ws_CIL_5", "SoaService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Env/TestMerge1/WebContent/wsdl/ws_CIL_5_SoaService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/Env/TestMerge1/WebContent/wsdl/ws_CIL_5_SoaService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SoaService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SoaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoaService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns SoaService
     */
    @WebEndpoint(name = "SoaService")
    public SoaService getSoaService() {
        return super.getPort(SoaService, SoaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoaService
     */
    @WebEndpoint(name = "SoaService")
    public SoaService getSoaService(WebServiceFeature... features) {
        return super.getPort(SoaService, SoaService.class, features);
    }

}
