package com.ericsson.services.ws_cil_5;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.12-soa-02
 * Wed Jan 27 04:38:43 CST 2016
 * Generated source version: 2.2.12-soa-02
 * 
 */
 
@WebService(targetNamespace = "http://ericsson.com/services/ws_CIL_5", name = "SoaService")
@XmlSeeAlso({com.ericsson.services.ws_cil_5.rateplansread.ObjectFactory.class, com.ericsson.services.ws_cil_5.customerread.ObjectFactory.class, com.lhsgroup.lhsws.money.ObjectFactory.class, com.lhsgroup.lhsws.svlany.ObjectFactory.class, com.ericsson.services.ws_cil_5.servicesread.ObjectFactory.class, com.ericsson.services.ws_cil_5.paymentarrangementsread.ObjectFactory.class, com.ericsson.services.ws_cil_5.addressesread.ObjectFactory.class, com.ericsson.services.ws_cil_5.contractssearch.ObjectFactory.class, com.ericsson.services.ws_cil_5.contractread.ObjectFactory.class, com.ericsson.services.ws_cil_5.sessionchange.ObjectFactory.class, com.ericsson.services.ws_cil_5.servicepackagesread.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SoaService {

    @WebResult(name = "addressesReadResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_5/addressesread", partName = "addressesReadResponse")
    @WebMethod
    public com.ericsson.services.ws_cil_5.addressesread.AddressesReadResponse addressesRead(
        @WebParam(partName = "addressesReadRequest", name = "addressesReadRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_5/addressesread")
        com.ericsson.services.ws_cil_5.addressesread.AddressesReadRequest addressesReadRequest
    );

    @WebResult(name = "customerReadResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_5/customerread", partName = "customerReadResponse")
    @WebMethod
    public com.ericsson.services.ws_cil_5.customerread.CustomerReadResponse customerRead(
        @WebParam(partName = "customerReadRequest", name = "customerReadRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_5/customerread")
        com.ericsson.services.ws_cil_5.customerread.CustomerReadRequest customerReadRequest
    );

    @WebResult(name = "contractsSearchResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_5/contractssearch", partName = "contractsSearchResponse")
    @WebMethod
    public com.ericsson.services.ws_cil_5.contractssearch.ContractsSearchResponse contractsSearch(
        @WebParam(partName = "contractsSearchRequest", name = "contractsSearchRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_5/contractssearch")
        com.ericsson.services.ws_cil_5.contractssearch.ContractsSearchRequest contractsSearchRequest
    );

    @WebResult(name = "paymentArrangementsReadResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_5/paymentarrangementsread", partName = "paymentArrangementsReadResponse")
    @WebMethod
    public com.ericsson.services.ws_cil_5.paymentarrangementsread.PaymentArrangementsReadResponse paymentArrangementsRead(
        @WebParam(partName = "paymentArrangementsReadRequest", name = "paymentArrangementsReadRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_5/paymentarrangementsread")
        com.ericsson.services.ws_cil_5.paymentarrangementsread.PaymentArrangementsReadRequest paymentArrangementsReadRequest
    );

    @WebResult(name = "contractReadResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_5/contractread", partName = "contractReadResponse")
    @WebMethod
    public com.ericsson.services.ws_cil_5.contractread.ContractReadResponse contractRead(
        @WebParam(partName = "contractReadRequest", name = "contractReadRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_5/contractread")
        com.ericsson.services.ws_cil_5.contractread.ContractReadRequest contractReadRequest
    );

    @WebResult(name = "servicesReadResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_5/servicesread", partName = "servicesReadResponse")
    @WebMethod
    public com.ericsson.services.ws_cil_5.servicesread.ServicesReadResponse servicesRead(
        @WebParam(partName = "servicesReadRequest", name = "servicesReadRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_5/servicesread")
        com.ericsson.services.ws_cil_5.servicesread.ServicesReadRequest servicesReadRequest
    );

    @WebResult(name = "servicePackagesReadResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_5/servicepackagesread", partName = "servicePackagesReadResponse")
    @WebMethod
    public com.ericsson.services.ws_cil_5.servicepackagesread.ServicePackagesReadResponse servicePackagesRead(
        @WebParam(partName = "servicePackagesReadRequest", name = "servicePackagesReadRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_5/servicepackagesread")
        com.ericsson.services.ws_cil_5.servicepackagesread.ServicePackagesReadRequest servicePackagesReadRequest
    );

    @WebResult(name = "rateplansReadResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_5/rateplansread", partName = "rateplansReadResponse")
    @WebMethod
    public com.ericsson.services.ws_cil_5.rateplansread.RateplansReadResponse rateplansRead(
        @WebParam(partName = "rateplansReadRequest", name = "rateplansReadRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_5/rateplansread")
        com.ericsson.services.ws_cil_5.rateplansread.RateplansReadRequest rateplansReadRequest
    );
}
