//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.12-08/23/2011 11:04 AM(mockbuild)-ea 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.27 at 02:15:54 AM CST 
//


package com.ericsson.tm.proxy.service.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ericsson.tm.proxy.service.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ericsson.tm.proxy.service.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PortalMessage.Header }
     * 
     */
    public PortalMessage.Header createPortalMessageHeader() {
        return new PortalMessage.Header();
    }

    /**
     * Create an instance of {@link PortalMessage.Response }
     * 
     */
    public PortalMessage.Response createPortalMessageResponse() {
        return new PortalMessage.Response();
    }

    /**
     * Create an instance of {@link PortalMessage.Response.LineItems }
     * 
     */
    public PortalMessage.Response.LineItems createPortalMessageResponseLineItems() {
        return new PortalMessage.Response.LineItems();
    }

    /**
     * Create an instance of {@link PortalMessage.Response.LineItems.LineItemXALiat.LineItemXA }
     * 
     */
    public PortalMessage.Response.LineItems.LineItemXALiat.LineItemXA createPortalMessageResponseLineItemsLineItemXALiatLineItemXA() {
        return new PortalMessage.Response.LineItems.LineItemXALiat.LineItemXA();
    }

    /**
     * Create an instance of {@link PortalMessage.Response.LineItems.ServiceAddress }
     * 
     */
    public PortalMessage.Response.LineItems.ServiceAddress createPortalMessageResponseLineItemsServiceAddress() {
        return new PortalMessage.Response.LineItems.ServiceAddress();
    }

    /**
     * Create an instance of {@link PortalMessage }
     * 
     */
    public PortalMessage createPortalMessage() {
        return new PortalMessage();
    }

    /**
     * Create an instance of {@link PortalMessage.Response.LineItems.LineItemXALiat }
     * 
     */
    public PortalMessage.Response.LineItems.LineItemXALiat createPortalMessageResponseLineItemsLineItemXALiat() {
        return new PortalMessage.Response.LineItems.LineItemXALiat();
    }

}
