//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.12-08/23/2011 11:04 AM(mockbuild)-ea 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.27 at 02:15:54 AM CST 
//


package com.ericsson.tm.proxy.service.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BusinessEvent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ReqRespType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MessageId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Response">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LineItems" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PartNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ServiceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="AssetID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="IntegrationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ProductName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ProductType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="PromotionIntegrationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ParentAssetID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ServicePointID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="SiteNameExchange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ServiceAddress" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="AddressID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="AddressType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="HouseUnitLot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="Floor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="BuildingName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="StreetType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="Section" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="Postcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="PremiseType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="TMIPV6LANAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="TMIPV6ReservationStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="TMIPV6WANAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DiscountPromotion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DiscountContract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DiscountPercentage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DiscountExpiryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="LineItemXALiat" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="LineItemXA" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                 &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ServicePointInstanceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="SiebelReservationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="BillingAccountRowID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ServiceTaxFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="TMPromotionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="TMPromotionStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="TMPromotionEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="TMIPTVBillingStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="TechnologyType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="PremiseType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ServicePassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DPLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="TMBiz100" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="MS365ExistingDomain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "response"
})
@XmlRootElement(name = "PortalMessage")
public class PortalMessage {

    @XmlElement(name = "Header", required = true)
    protected PortalMessage.Header header;
    @XmlElement(name = "Response", required = true)
    protected PortalMessage.Response response;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link PortalMessage.Header }
     *     
     */
    public PortalMessage.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortalMessage.Header }
     *     
     */
    public void setHeader(PortalMessage.Header value) {
        this.header = value;
    }

    public boolean isSetHeader() {
        return (this.header!= null);
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link PortalMessage.Response }
     *     
     */
    public PortalMessage.Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortalMessage.Response }
     *     
     */
    public void setResponse(PortalMessage.Response value) {
        this.response = value;
    }

    public boolean isSetResponse() {
        return (this.response!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BusinessEvent" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ReqRespType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MessageId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "businessEvent",
        "timestamp",
        "reqRespType",
        "messageId",
        "errorCode",
        "errorMessage"
    })
    public static class Header {

        @XmlElement(name = "BusinessEvent", required = true)
        protected String businessEvent;
        @XmlElement(name = "Timestamp", required = true)
        protected String timestamp;
        @XmlElement(name = "ReqRespType", required = true)
        protected String reqRespType;
        @XmlElement(name = "MessageId")
        protected String messageId;
        @XmlElement(name = "ErrorCode")
        protected String errorCode;
        @XmlElement(name = "ErrorMessage")
        protected String errorMessage;

        /**
         * Gets the value of the businessEvent property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBusinessEvent() {
            return businessEvent;
        }

        /**
         * Sets the value of the businessEvent property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBusinessEvent(String value) {
            this.businessEvent = value;
        }

        public boolean isSetBusinessEvent() {
            return (this.businessEvent!= null);
        }

        /**
         * Gets the value of the timestamp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTimestamp() {
            return timestamp;
        }

        /**
         * Sets the value of the timestamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTimestamp(String value) {
            this.timestamp = value;
        }

        public boolean isSetTimestamp() {
            return (this.timestamp!= null);
        }

        /**
         * Gets the value of the reqRespType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReqRespType() {
            return reqRespType;
        }

        /**
         * Sets the value of the reqRespType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReqRespType(String value) {
            this.reqRespType = value;
        }

        public boolean isSetReqRespType() {
            return (this.reqRespType!= null);
        }

        /**
         * Gets the value of the messageId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessageId() {
            return messageId;
        }

        /**
         * Sets the value of the messageId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessageId(String value) {
            this.messageId = value;
        }

        public boolean isSetMessageId() {
            return (this.messageId!= null);
        }

        /**
         * Gets the value of the errorCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrorCode() {
            return errorCode;
        }

        /**
         * Sets the value of the errorCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrorCode(String value) {
            this.errorCode = value;
        }

        public boolean isSetErrorCode() {
            return (this.errorCode!= null);
        }

        /**
         * Gets the value of the errorMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrorMessage() {
            return errorMessage;
        }

        /**
         * Sets the value of the errorMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrorMessage(String value) {
            this.errorMessage = value;
        }

        public boolean isSetErrorMessage() {
            return (this.errorMessage!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LineItems" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PartNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ServiceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="AssetID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="IntegrationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ProductName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ProductType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="PromotionIntegrationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ParentAssetID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ServicePointID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="SiteNameExchange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ServiceAddress" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="AddressID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="AddressType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="HouseUnitLot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="Floor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="BuildingName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="StreetType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="Section" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="Postcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="PremiseType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="TMIPV6LANAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="TMIPV6ReservationStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="TMIPV6WANAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DiscountPromotion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DiscountContract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DiscountPercentage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DiscountExpiryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="LineItemXALiat" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="LineItemXA" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                       &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ServicePointInstanceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="SiebelReservationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="BillingAccountRowID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ServiceTaxFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="TMPromotionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="TMPromotionStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="TMPromotionEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="TMIPTVBillingStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="TechnologyType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="PremiseType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ServicePassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DPLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="TMBiz100" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="MS365ExistingDomain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lineItems"
    })
    public static class Response {

        @XmlElement(name = "LineItems")
        protected List<PortalMessage.Response.LineItems> lineItems;

        /**
         * Gets the value of the lineItems property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the lineItems property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLineItems().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PortalMessage.Response.LineItems }
         * 
         * 
         */
        public List<PortalMessage.Response.LineItems> getLineItems() {
            if (lineItems == null) {
                lineItems = new ArrayList<PortalMessage.Response.LineItems>();
            }
            return this.lineItems;
        }

        public boolean isSetLineItems() {
            return ((this.lineItems!= null)&&(!this.lineItems.isEmpty()));
        }

        public void unsetLineItems() {
            this.lineItems = null;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PartNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ServiceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="AssetID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="IntegrationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ProductName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ProductType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="PromotionIntegrationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ParentAssetID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ServicePointID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="SiteNameExchange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ServiceAddress" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="AddressID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="AddressType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="HouseUnitLot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="Floor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="BuildingName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="StreetType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="Section" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="Postcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="PremiseType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="TMIPV6LANAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TMIPV6ReservationStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TMIPV6WANAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DiscountPromotion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DiscountContract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DiscountPercentage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DiscountExpiryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="LineItemXALiat" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="LineItemXA" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                             &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ServicePointInstanceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="SiebelReservationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="BillingAccountRowID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ServiceTaxFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TMPromotionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TMPromotionStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TMPromotionEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TMIPTVBillingStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TechnologyType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="PremiseType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ServicePassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DPLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TMBiz100" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="MS365ExistingDomain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "partNum",
            "serviceID",
            "assetID",
            "integrationID",
            "productName",
            "productType",
            "promotionIntegrationID",
            "parentAssetID",
            "servicePointID",
            "startDate",
            "siteNameExchange",
            "serviceAddress",
            "tmipv6LANAddress",
            "tmipv6ReservationStatus",
            "tmipv6WANAddress",
            "discountPromotion",
            "discountContract",
            "discountPercentage",
            "discountExpiryDate",
            "lineItemXALiat",
            "servicePointInstanceID",
            "siebelReservationID",
            "quantity",
            "billingAccountRowID",
            "serviceTaxFlag",
            "tmPromotionName",
            "tmPromotionStartDate",
            "tmPromotionEndDate",
            "tmiptvBillingStartDate",
            "technologyType",
            "premiseType",
            "servicePassword",
            "dpLocation",
            "tmBiz100",
            "ms365ExistingDomain"
        })
        public static class LineItems {

            @XmlElement(name = "PartNum")
            protected String partNum;
            @XmlElement(name = "ServiceID")
            protected String serviceID;
            @XmlElement(name = "AssetID")
            protected String assetID;
            @XmlElement(name = "IntegrationID")
            protected String integrationID;
            @XmlElement(name = "ProductName")
            protected String productName;
            @XmlElement(name = "ProductType")
            protected String productType;
            @XmlElement(name = "PromotionIntegrationID")
            protected String promotionIntegrationID;
            @XmlElement(name = "ParentAssetID")
            protected String parentAssetID;
            @XmlElement(name = "ServicePointID")
            protected String servicePointID;
            @XmlElement(name = "StartDate")
            protected String startDate;
            @XmlElement(name = "SiteNameExchange")
            protected String siteNameExchange;
            @XmlElement(name = "ServiceAddress")
            protected PortalMessage.Response.LineItems.ServiceAddress serviceAddress;
            @XmlElement(name = "TMIPV6LANAddress")
            protected String tmipv6LANAddress;
            @XmlElement(name = "TMIPV6ReservationStatus")
            protected String tmipv6ReservationStatus;
            @XmlElement(name = "TMIPV6WANAddress")
            protected String tmipv6WANAddress;
            @XmlElement(name = "DiscountPromotion")
            protected String discountPromotion;
            @XmlElement(name = "DiscountContract")
            protected String discountContract;
            @XmlElement(name = "DiscountPercentage")
            protected String discountPercentage;
            @XmlElement(name = "DiscountExpiryDate")
            protected String discountExpiryDate;
            @XmlElement(name = "LineItemXALiat")
            protected PortalMessage.Response.LineItems.LineItemXALiat lineItemXALiat;
            @XmlElement(name = "ServicePointInstanceID")
            protected String servicePointInstanceID;
            @XmlElement(name = "SiebelReservationID")
            protected String siebelReservationID;
            @XmlElement(name = "Quantity")
            protected String quantity;
            @XmlElement(name = "BillingAccountRowID")
            protected String billingAccountRowID;
            @XmlElement(name = "ServiceTaxFlag")
            protected String serviceTaxFlag;
            @XmlElement(name = "TMPromotionName")
            protected String tmPromotionName;
            @XmlElement(name = "TMPromotionStartDate")
            protected String tmPromotionStartDate;
            @XmlElement(name = "TMPromotionEndDate")
            protected String tmPromotionEndDate;
            @XmlElement(name = "TMIPTVBillingStartDate")
            protected String tmiptvBillingStartDate;
            @XmlElement(name = "TechnologyType")
            protected String technologyType;
            @XmlElement(name = "PremiseType")
            protected String premiseType;
            @XmlElement(name = "ServicePassword")
            protected String servicePassword;
            @XmlElement(name = "DPLocation")
            protected String dpLocation;
            @XmlElement(name = "TMBiz100")
            protected String tmBiz100;
            @XmlElement(name = "MS365ExistingDomain")
            protected String ms365ExistingDomain;

            /**
             * Gets the value of the partNum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPartNum() {
                return partNum;
            }

            /**
             * Sets the value of the partNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPartNum(String value) {
                this.partNum = value;
            }

            public boolean isSetPartNum() {
                return (this.partNum!= null);
            }

            /**
             * Gets the value of the serviceID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServiceID() {
                return serviceID;
            }

            /**
             * Sets the value of the serviceID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServiceID(String value) {
                this.serviceID = value;
            }

            public boolean isSetServiceID() {
                return (this.serviceID!= null);
            }

            /**
             * Gets the value of the assetID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAssetID() {
                return assetID;
            }

            /**
             * Sets the value of the assetID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAssetID(String value) {
                this.assetID = value;
            }

            public boolean isSetAssetID() {
                return (this.assetID!= null);
            }

            /**
             * Gets the value of the integrationID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIntegrationID() {
                return integrationID;
            }

            /**
             * Sets the value of the integrationID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIntegrationID(String value) {
                this.integrationID = value;
            }

            public boolean isSetIntegrationID() {
                return (this.integrationID!= null);
            }

            /**
             * Gets the value of the productName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductName() {
                return productName;
            }

            /**
             * Sets the value of the productName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductName(String value) {
                this.productName = value;
            }

            public boolean isSetProductName() {
                return (this.productName!= null);
            }

            /**
             * Gets the value of the productType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductType() {
                return productType;
            }

            /**
             * Sets the value of the productType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductType(String value) {
                this.productType = value;
            }

            public boolean isSetProductType() {
                return (this.productType!= null);
            }

            /**
             * Gets the value of the promotionIntegrationID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPromotionIntegrationID() {
                return promotionIntegrationID;
            }

            /**
             * Sets the value of the promotionIntegrationID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPromotionIntegrationID(String value) {
                this.promotionIntegrationID = value;
            }

            public boolean isSetPromotionIntegrationID() {
                return (this.promotionIntegrationID!= null);
            }

            /**
             * Gets the value of the parentAssetID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getParentAssetID() {
                return parentAssetID;
            }

            /**
             * Sets the value of the parentAssetID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setParentAssetID(String value) {
                this.parentAssetID = value;
            }

            public boolean isSetParentAssetID() {
                return (this.parentAssetID!= null);
            }

            /**
             * Gets the value of the servicePointID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServicePointID() {
                return servicePointID;
            }

            /**
             * Sets the value of the servicePointID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServicePointID(String value) {
                this.servicePointID = value;
            }

            public boolean isSetServicePointID() {
                return (this.servicePointID!= null);
            }

            /**
             * Gets the value of the startDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStartDate() {
                return startDate;
            }

            /**
             * Sets the value of the startDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStartDate(String value) {
                this.startDate = value;
            }

            public boolean isSetStartDate() {
                return (this.startDate!= null);
            }

            /**
             * Gets the value of the siteNameExchange property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSiteNameExchange() {
                return siteNameExchange;
            }

            /**
             * Sets the value of the siteNameExchange property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSiteNameExchange(String value) {
                this.siteNameExchange = value;
            }

            public boolean isSetSiteNameExchange() {
                return (this.siteNameExchange!= null);
            }

            /**
             * Gets the value of the serviceAddress property.
             * 
             * @return
             *     possible object is
             *     {@link PortalMessage.Response.LineItems.ServiceAddress }
             *     
             */
            public PortalMessage.Response.LineItems.ServiceAddress getServiceAddress() {
                return serviceAddress;
            }

            /**
             * Sets the value of the serviceAddress property.
             * 
             * @param value
             *     allowed object is
             *     {@link PortalMessage.Response.LineItems.ServiceAddress }
             *     
             */
            public void setServiceAddress(PortalMessage.Response.LineItems.ServiceAddress value) {
                this.serviceAddress = value;
            }

            public boolean isSetServiceAddress() {
                return (this.serviceAddress!= null);
            }

            /**
             * Gets the value of the tmipv6LANAddress property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTMIPV6LANAddress() {
                return tmipv6LANAddress;
            }

            /**
             * Sets the value of the tmipv6LANAddress property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTMIPV6LANAddress(String value) {
                this.tmipv6LANAddress = value;
            }

            public boolean isSetTMIPV6LANAddress() {
                return (this.tmipv6LANAddress!= null);
            }

            /**
             * Gets the value of the tmipv6ReservationStatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTMIPV6ReservationStatus() {
                return tmipv6ReservationStatus;
            }

            /**
             * Sets the value of the tmipv6ReservationStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTMIPV6ReservationStatus(String value) {
                this.tmipv6ReservationStatus = value;
            }

            public boolean isSetTMIPV6ReservationStatus() {
                return (this.tmipv6ReservationStatus!= null);
            }

            /**
             * Gets the value of the tmipv6WANAddress property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTMIPV6WANAddress() {
                return tmipv6WANAddress;
            }

            /**
             * Sets the value of the tmipv6WANAddress property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTMIPV6WANAddress(String value) {
                this.tmipv6WANAddress = value;
            }

            public boolean isSetTMIPV6WANAddress() {
                return (this.tmipv6WANAddress!= null);
            }

            /**
             * Gets the value of the discountPromotion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDiscountPromotion() {
                return discountPromotion;
            }

            /**
             * Sets the value of the discountPromotion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDiscountPromotion(String value) {
                this.discountPromotion = value;
            }

            public boolean isSetDiscountPromotion() {
                return (this.discountPromotion!= null);
            }

            /**
             * Gets the value of the discountContract property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDiscountContract() {
                return discountContract;
            }

            /**
             * Sets the value of the discountContract property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDiscountContract(String value) {
                this.discountContract = value;
            }

            public boolean isSetDiscountContract() {
                return (this.discountContract!= null);
            }

            /**
             * Gets the value of the discountPercentage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDiscountPercentage() {
                return discountPercentage;
            }

            /**
             * Sets the value of the discountPercentage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDiscountPercentage(String value) {
                this.discountPercentage = value;
            }

            public boolean isSetDiscountPercentage() {
                return (this.discountPercentage!= null);
            }

            /**
             * Gets the value of the discountExpiryDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDiscountExpiryDate() {
                return discountExpiryDate;
            }

            /**
             * Sets the value of the discountExpiryDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDiscountExpiryDate(String value) {
                this.discountExpiryDate = value;
            }

            public boolean isSetDiscountExpiryDate() {
                return (this.discountExpiryDate!= null);
            }

            /**
             * Gets the value of the lineItemXALiat property.
             * 
             * @return
             *     possible object is
             *     {@link PortalMessage.Response.LineItems.LineItemXALiat }
             *     
             */
            public PortalMessage.Response.LineItems.LineItemXALiat getLineItemXALiat() {
                return lineItemXALiat;
            }

            /**
             * Sets the value of the lineItemXALiat property.
             * 
             * @param value
             *     allowed object is
             *     {@link PortalMessage.Response.LineItems.LineItemXALiat }
             *     
             */
            public void setLineItemXALiat(PortalMessage.Response.LineItems.LineItemXALiat value) {
                this.lineItemXALiat = value;
            }

            public boolean isSetLineItemXALiat() {
                return (this.lineItemXALiat!= null);
            }

            /**
             * Gets the value of the servicePointInstanceID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServicePointInstanceID() {
                return servicePointInstanceID;
            }

            /**
             * Sets the value of the servicePointInstanceID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServicePointInstanceID(String value) {
                this.servicePointInstanceID = value;
            }

            public boolean isSetServicePointInstanceID() {
                return (this.servicePointInstanceID!= null);
            }

            /**
             * Gets the value of the siebelReservationID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSiebelReservationID() {
                return siebelReservationID;
            }

            /**
             * Sets the value of the siebelReservationID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSiebelReservationID(String value) {
                this.siebelReservationID = value;
            }

            public boolean isSetSiebelReservationID() {
                return (this.siebelReservationID!= null);
            }

            /**
             * Gets the value of the quantity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQuantity() {
                return quantity;
            }

            /**
             * Sets the value of the quantity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQuantity(String value) {
                this.quantity = value;
            }

            public boolean isSetQuantity() {
                return (this.quantity!= null);
            }

            /**
             * Gets the value of the billingAccountRowID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBillingAccountRowID() {
                return billingAccountRowID;
            }

            /**
             * Sets the value of the billingAccountRowID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBillingAccountRowID(String value) {
                this.billingAccountRowID = value;
            }

            public boolean isSetBillingAccountRowID() {
                return (this.billingAccountRowID!= null);
            }

            /**
             * Gets the value of the serviceTaxFlag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServiceTaxFlag() {
                return serviceTaxFlag;
            }

            /**
             * Sets the value of the serviceTaxFlag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServiceTaxFlag(String value) {
                this.serviceTaxFlag = value;
            }

            public boolean isSetServiceTaxFlag() {
                return (this.serviceTaxFlag!= null);
            }

            /**
             * Gets the value of the tmPromotionName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTMPromotionName() {
                return tmPromotionName;
            }

            /**
             * Sets the value of the tmPromotionName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTMPromotionName(String value) {
                this.tmPromotionName = value;
            }

            public boolean isSetTMPromotionName() {
                return (this.tmPromotionName!= null);
            }

            /**
             * Gets the value of the tmPromotionStartDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTMPromotionStartDate() {
                return tmPromotionStartDate;
            }

            /**
             * Sets the value of the tmPromotionStartDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTMPromotionStartDate(String value) {
                this.tmPromotionStartDate = value;
            }

            public boolean isSetTMPromotionStartDate() {
                return (this.tmPromotionStartDate!= null);
            }

            /**
             * Gets the value of the tmPromotionEndDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTMPromotionEndDate() {
                return tmPromotionEndDate;
            }

            /**
             * Sets the value of the tmPromotionEndDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTMPromotionEndDate(String value) {
                this.tmPromotionEndDate = value;
            }

            public boolean isSetTMPromotionEndDate() {
                return (this.tmPromotionEndDate!= null);
            }

            /**
             * Gets the value of the tmiptvBillingStartDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTMIPTVBillingStartDate() {
                return tmiptvBillingStartDate;
            }

            /**
             * Sets the value of the tmiptvBillingStartDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTMIPTVBillingStartDate(String value) {
                this.tmiptvBillingStartDate = value;
            }

            public boolean isSetTMIPTVBillingStartDate() {
                return (this.tmiptvBillingStartDate!= null);
            }

            /**
             * Gets the value of the technologyType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTechnologyType() {
                return technologyType;
            }

            /**
             * Sets the value of the technologyType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTechnologyType(String value) {
                this.technologyType = value;
            }

            public boolean isSetTechnologyType() {
                return (this.technologyType!= null);
            }

            /**
             * Gets the value of the premiseType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPremiseType() {
                return premiseType;
            }

            /**
             * Sets the value of the premiseType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPremiseType(String value) {
                this.premiseType = value;
            }

            public boolean isSetPremiseType() {
                return (this.premiseType!= null);
            }

            /**
             * Gets the value of the servicePassword property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServicePassword() {
                return servicePassword;
            }

            /**
             * Sets the value of the servicePassword property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServicePassword(String value) {
                this.servicePassword = value;
            }

            public boolean isSetServicePassword() {
                return (this.servicePassword!= null);
            }

            /**
             * Gets the value of the dpLocation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDPLocation() {
                return dpLocation;
            }

            /**
             * Sets the value of the dpLocation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDPLocation(String value) {
                this.dpLocation = value;
            }

            public boolean isSetDPLocation() {
                return (this.dpLocation!= null);
            }

            /**
             * Gets the value of the tmBiz100 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTMBiz100() {
                return tmBiz100;
            }

            /**
             * Sets the value of the tmBiz100 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTMBiz100(String value) {
                this.tmBiz100 = value;
            }

            public boolean isSetTMBiz100() {
                return (this.tmBiz100 != null);
            }

            /**
             * Gets the value of the ms365ExistingDomain property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMS365ExistingDomain() {
                return ms365ExistingDomain;
            }

            /**
             * Sets the value of the ms365ExistingDomain property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMS365ExistingDomain(String value) {
                this.ms365ExistingDomain = value;
            }

            public boolean isSetMS365ExistingDomain() {
                return (this.ms365ExistingDomain!= null);
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="LineItemXA" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "lineItemXA"
            })
            public static class LineItemXALiat {

                @XmlElement(name = "LineItemXA", required = true)
                protected List<PortalMessage.Response.LineItems.LineItemXALiat.LineItemXA> lineItemXA;

                /**
                 * Gets the value of the lineItemXA property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the lineItemXA property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getLineItemXA().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link PortalMessage.Response.LineItems.LineItemXALiat.LineItemXA }
                 * 
                 * 
                 */
                public List<PortalMessage.Response.LineItems.LineItemXALiat.LineItemXA> getLineItemXA() {
                    if (lineItemXA == null) {
                        lineItemXA = new ArrayList<PortalMessage.Response.LineItems.LineItemXALiat.LineItemXA>();
                    }
                    return this.lineItemXA;
                }

                public boolean isSetLineItemXA() {
                    return ((this.lineItemXA!= null)&&(!this.lineItemXA.isEmpty()));
                }

                public void unsetLineItemXA() {
                    this.lineItemXA = null;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "name",
                    "value"
                })
                public static class LineItemXA {

                    @XmlElement(name = "Name")
                    protected String name;
                    @XmlElement(name = "Value")
                    protected String value;

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    public boolean isSetName() {
                        return (this.name!= null);
                    }

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    public boolean isSetValue() {
                        return (this.value!= null);
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="AddressID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="AddressType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="HouseUnitLot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="Floor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="BuildingName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="StreetType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="Section" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="Postcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="PremiseType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "addressID",
                "addressType",
                "houseUnitLot",
                "floor",
                "buildingName",
                "streetType",
                "streetName",
                "section",
                "city",
                "state",
                "postcode",
                "country",
                "premiseType"
            })
            public static class ServiceAddress {

                @XmlElement(name = "AddressID")
                protected String addressID;
                @XmlElement(name = "AddressType")
                protected String addressType;
                @XmlElement(name = "HouseUnitLot")
                protected String houseUnitLot;
                @XmlElement(name = "Floor")
                protected String floor;
                @XmlElement(name = "BuildingName")
                protected String buildingName;
                @XmlElement(name = "StreetType")
                protected String streetType;
                @XmlElement(name = "StreetName")
                protected String streetName;
                @XmlElement(name = "Section")
                protected String section;
                @XmlElement(name = "City")
                protected String city;
                @XmlElement(name = "State")
                protected String state;
                @XmlElement(name = "Postcode")
                protected String postcode;
                @XmlElement(name = "Country")
                protected String country;
                @XmlElement(name = "PremiseType")
                protected String premiseType;

                /**
                 * Gets the value of the addressID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAddressID() {
                    return addressID;
                }

                /**
                 * Sets the value of the addressID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAddressID(String value) {
                    this.addressID = value;
                }

                public boolean isSetAddressID() {
                    return (this.addressID!= null);
                }

                /**
                 * Gets the value of the addressType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAddressType() {
                    return addressType;
                }

                /**
                 * Sets the value of the addressType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAddressType(String value) {
                    this.addressType = value;
                }

                public boolean isSetAddressType() {
                    return (this.addressType!= null);
                }

                /**
                 * Gets the value of the houseUnitLot property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHouseUnitLot() {
                    return houseUnitLot;
                }

                /**
                 * Sets the value of the houseUnitLot property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHouseUnitLot(String value) {
                    this.houseUnitLot = value;
                }

                public boolean isSetHouseUnitLot() {
                    return (this.houseUnitLot!= null);
                }

                /**
                 * Gets the value of the floor property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFloor() {
                    return floor;
                }

                /**
                 * Sets the value of the floor property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFloor(String value) {
                    this.floor = value;
                }

                public boolean isSetFloor() {
                    return (this.floor!= null);
                }

                /**
                 * Gets the value of the buildingName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBuildingName() {
                    return buildingName;
                }

                /**
                 * Sets the value of the buildingName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBuildingName(String value) {
                    this.buildingName = value;
                }

                public boolean isSetBuildingName() {
                    return (this.buildingName!= null);
                }

                /**
                 * Gets the value of the streetType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStreetType() {
                    return streetType;
                }

                /**
                 * Sets the value of the streetType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStreetType(String value) {
                    this.streetType = value;
                }

                public boolean isSetStreetType() {
                    return (this.streetType!= null);
                }

                /**
                 * Gets the value of the streetName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStreetName() {
                    return streetName;
                }

                /**
                 * Sets the value of the streetName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStreetName(String value) {
                    this.streetName = value;
                }

                public boolean isSetStreetName() {
                    return (this.streetName!= null);
                }

                /**
                 * Gets the value of the section property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSection() {
                    return section;
                }

                /**
                 * Sets the value of the section property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSection(String value) {
                    this.section = value;
                }

                public boolean isSetSection() {
                    return (this.section!= null);
                }

                /**
                 * Gets the value of the city property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCity() {
                    return city;
                }

                /**
                 * Sets the value of the city property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCity(String value) {
                    this.city = value;
                }

                public boolean isSetCity() {
                    return (this.city!= null);
                }

                /**
                 * Gets the value of the state property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getState() {
                    return state;
                }

                /**
                 * Sets the value of the state property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setState(String value) {
                    this.state = value;
                }

                public boolean isSetState() {
                    return (this.state!= null);
                }

                /**
                 * Gets the value of the postcode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPostcode() {
                    return postcode;
                }

                /**
                 * Sets the value of the postcode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPostcode(String value) {
                    this.postcode = value;
                }

                public boolean isSetPostcode() {
                    return (this.postcode!= null);
                }

                /**
                 * Gets the value of the country property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCountry() {
                    return country;
                }

                /**
                 * Sets the value of the country property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCountry(String value) {
                    this.country = value;
                }

                public boolean isSetCountry() {
                    return (this.country!= null);
                }

                /**
                 * Gets the value of the premiseType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPremiseType() {
                    return premiseType;
                }

                /**
                 * Sets the value of the premiseType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPremiseType(String value) {
                    this.premiseType = value;
                }

                public boolean isSetPremiseType() {
                    return (this.premiseType!= null);
                }

            }

        }

    }

}
