package com.ericsson.tm.cbio.servicepackagesread;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.12-soa-02
 * Tue Jan 26 11:30:10 CST 2016
 * Generated source version: 2.2.12-soa-02
 * 
 */
 
@WebService(targetNamespace = "http://ericsson.com/services/ws_CIL_5", name = "ServicePackagesReadService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServicePackagesReadService {

    @WebResult(name = "servicePackagesReadResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_5/servicepackagesread", partName = "servicePackagesReadResponse")
    @WebMethod
    public ServicePackagesReadResponse servicePackagesRead(
        @WebParam(partName = "servicePackagesReadRequest", name = "servicePackagesReadRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_5/servicepackagesread")
        ServicePackagesReadRequest servicePackagesReadRequest
    );
}
