package com.ericsson.tm.cbio.contractread;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.12-soa-02
 * Tue Jan 26 11:22:51 CST 2016
 * Generated source version: 2.2.12-soa-02
 * 
 */
 
@WebService(targetNamespace = "http://ericsson.com/services/ws_CIL_5", name = "ContractReadService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ContractReadService {

    @WebResult(name = "contractReadResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_5/contractread", partName = "contractReadResponse")
    @WebMethod
    public ContractReadResponse contractRead(
        @WebParam(partName = "contractReadRequest", name = "contractReadRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_5/contractread")
        ContractReadRequest contractReadRequest
    );
}
