//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.12-08/23/2011 11:04 AM(mockbuild)-ea 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.27 at 02:15:54 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "")
package com.ericsson.tm.proxy.customer.request;
