package com.ericsson.tm.cbio.contractsearch;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.12-soa-02
 * Tue Jan 26 11:09:45 CST 2016
 * Generated source version: 2.2.12-soa-02
 * 
 */
 
/*@WebService(targetNamespace = "http://ericsson.com/services/ws_CIL_5", name = "ContractsSearchService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ContractsSearchService {

    @WebResult(name = "contractsSearchResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_5/contractssearch", partName = "contractsSearchResponse")
    @WebMethod
    public ContractsSearchResponse contractsSearch(
        @WebParam(partName = "contractsSearchRequest", name = "contractsSearchRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_5/contractssearch")
        ContractsSearchRequest contractsSearchRequest
    );
}*/

@WebService
public interface ContractsSearchService {

    @WebMethod
    public ContractsSearchResponse contractsSearch(
        ContractsSearchRequest contractsSearchRequest
    );
}
