package com.ericsson.tm.cbio.addressesread;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.12-soa-02
 * Tue Jan 26 11:26:16 CST 2016
 * Generated source version: 2.2.12-soa-02
 * 
 */
 
@WebService(targetNamespace = "http://ericsson.com/services/ws_CIL_5", name = "AddressesReadService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AddressesReadService {

    @WebResult(name = "addressesReadResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_5/addressesread", partName = "addressesReadResponse")
    @WebMethod
    public AddressesReadResponse addressesRead(
        @WebParam(partName = "addressesReadRequest", name = "addressesReadRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_5/addressesread")
        AddressesReadRequest addressesReadRequest
    );
}
