package com.ericsson.tm.proxy.test;

public class TestXml {

	public static final String TEST_RESP = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><PortalMessage>"
			+ "  <Header>"
			+ "    <BusinessEvent>CustomerProfileRetrieve</BusinessEvent>"
			+ "    <Timestamp>01/05/2016 12:26:33</Timestamp>"
			+ "    <ReqResType>Response</ReqResType>"
			+ "    <ErrorCode/>"
			+ "    <ErrorMessage/>"
			+ "  </Header>"
			+ "  <Response>"
			+ "    <CustomerAccount>"
			+ "      <AccountNo>1-10E2Y4D</AccountNo>"
			+ "      <CustomerName>CHUAH SAI LING</CustomerName>"
			+ "      <SegmentCode>R40</SegmentCode>"
			+ "      <SegmentGroup>Consumer</SegmentGroup>"
			+ "      <PrimaryIDType>New NRIC</PrimaryIDType>"
			+ "      <PrimaryIDNo>760911-14-5342</PrimaryIDNo>"
			+ "      <TMExternalSource>Customer Portal</TMExternalSource>"
			+ "      <Blacklist>Not Applicable</Blacklist>"
			+ "      <MobilePhone>0123389899</MobilePhone>"
			+ "      <OfficePhone/>"
			+ "      <HomePhone/>"
			+ "      <ContactMethod>Mobile</ContactMethod>"
			+ "      <Industry/>"
			+ "      <EmailAddress>sl1109@yahoo.com</EmailAddress>"
			+ "      <FaxNumber/>"
			+ "      <ExpiryDate/>"
			+ "      <CustomerAddress>"
			+ "        <AddressType>Landed</AddressType>"
			+ "        <HouseUnitLot>12</HouseUnitLot>"
			+ "        <Postcode>40170</Postcode>"
			+ "        <Floor/>"
			+ "        <BuildingName/>"
			+ "        <StreetType>JALAN</StreetType>"
			+ "        <StreetName>SETIA NUSANTARA U13/22U</StreetName>"
			+ "        <Section>BANDAR ECO-SETIA SEKSYEN U13</Section>"
			+ "        <City>SHAH ALAM</City>"
			+ "        <State>SELANGOR</State>"
			+ "        <Country>MALAYSIA</Country>"
			+ "        <TMAddressID>1-10E2XZ6</TMAddressID>"
			+ "      </CustomerAddress>"
			+ "      <Priority>P04</Priority>"
			+ "      <PassportCountry/>"
			+ "      <RegisteredAddress>"
			+ "        <AddressType>Landed</AddressType>"
			+ "        <HouseUnitLot>12</HouseUnitLot>"
			+ "        <Postcode>40170</Postcode>"
			+ "        <Floor/>"
			+ "        <BuildingName/>"
			+ "        <StreetType>JALAN</StreetType>"
			+ "        <StreetName>SETIA NUSANTARA U13/22U</StreetName>"
			+ "        <Section>BANDAR ECO-SETIA SEKSYEN U13</Section>"
			+ "        <City>SHAH ALAM</City>"
			+ "        <State>SELANGOR</State>"
			+ "        <Country>MALAYSIA</Country>"
			+ "        <TMAddressID>1-10E2XZ6</TMAddressID>"
			+ "      </RegisteredAddress>"
			+ "      <ServiceProvider/>"
			+ "      <LARSRewardsNo>6364020012068370</LARSRewardsNo>"
			+ "      <LARSMembershipNo>71206823</LARSMembershipNo>"
			+ "      <LARSMemberCategory>Authorised</LARSMemberCategory>"
			+ "      <LARSMemberStatus>Active</LARSMemberStatus>"
			+ "      <LARSTotalPoint>7117</LARSTotalPoint>"
			+ "      <LARSTotalPointDate>11/22/2015</LARSTotalPointDate>"
			+ "      <LARSPointExpiry>30000</LARSPointExpiry>"
			+ "      <LARSPointExpiryDate>11/30/2015</LARSPointExpiryDate>"
			+ "      <LARSLastEarnTrnDate>11/16/2015</LARSLastEarnTrnDate>"
			+ "      <LARSLastEarnTrnDesc>Reward Scheme</LARSLastEarnTrnDesc>"
			+ "      <LARSLastEarnTrnPoint>338</LARSLastEarnTrnPoint>"
			+ "      <LARSLastRedemTrnDate/>"
			+ "      <LARSLastRedemTrnDesc/>"
			+ "      <LARSLastRedemTrnPoint/>"
			+ "      <LARSProfileEnrollFlag>N</LARSProfileEnrollFlag>"
			+ "      <TMBRNSubType/>"
			+ "    </CustomerAccount>"
			+ "    <NonConsumerDemographics>"
			+ "      <RetailIndustry/>"
			+ "      <NatureOfBusiness/>"
			+ "      <CompanyAnnualRevenue/>"
			+ "      <NoOfEmployees/>"
			+ "      <NoOfBranches/>"
			+ "      <HeadquarterLocation/>"
			+ "    </NonConsumerDemographics>"
			+ "    <ConsumerDemographics>"
			+ "      <Gender/>"
			+ "      <Race>No Answer Given</Race>"
			+ "      <Occupation>No Answer Given</Occupation>"
			+ "      <JobTitle/>"
			+ "      <DateOfBirth>09/11/1976</DateOfBirth>"
			+ "      <Nationality>No Answer Given</Nationality>"
			+ "      <MaritalStatus>No Answer Given</MaritalStatus>"
			+ "      <ChildrenInAge7to21>"
			+ "        <Name>No Answer Given</Name>"
			+ "        <Value>No Answer Given</Value>"
			+ "      </ChildrenInAge7to21>"
			+ "      <MonthlyHouseholdIncome>No Answer Given</MonthlyHouseholdIncome>"
			+ "      <HouseholdSize>No Answer Given</HouseholdSize>"
			+ "      <HouseOwnership>No Answer Given</HouseOwnership>"
			+ "      <StayingWith/>"
			+ "      <PrimaryFestiveCelebration/>"
			+ "      <Hobbies>"
			+ "        <RowId>1-1F3MYTS</RowId>"
			+ "        <Name>Computer &amp; Internet</Name>"
			+ "        <Value>Computer &amp; Internet</Value>"
			+ "      </Hobbies>"
			+ "      <Hobbies>"
			+ "        <RowId>1-1F3MYTR</RowId>"
			+ "        <Name>Cooking &amp; Gardening</Name>"
			+ "        <Value>Cooking &amp; Gardening</Value>"
			+ "      </Hobbies>"
			+ "      <Hobbies>"
			+ "        <RowId>1-1F3MYTN</RowId>"
			+ "        <Name>Fashion &amp; Design</Name>"
			+ "        <Value>Fashion &amp; Design</Value>"
			+ "      </Hobbies>"
			+ "      <Hobbies>"
			+ "        <RowId>1-1F3MYTO</RowId>"
			+ "        <Name>Movie &amp; Theatre</Name>"
			+ "        <Value>Movie &amp; Theatre</Value>"
			+ "      </Hobbies>"
			+ "      <Hobbies>"
			+ "        <RowId>1-3I5C8T4</RowId>"
			+ "        <Name>No Answer Given</Name>"
			+ "        <Value>No Answer Given</Value>"
			+ "      </Hobbies>"
			+ "      <Hobbies>"
			+ "        <RowId>1-1F3MYTQ</RowId>"
			+ "        <Name>Reading</Name>"
			+ "        <Value>Reading</Value>"
			+ "      </Hobbies>"
			+ "      <Hobbies>"
			+ "        <RowId>1-1F3MYTU</RowId>"
			+ "        <Name>Shopping</Name>"
			+ "        <Value>Shopping</Value>"
			+ "      </Hobbies>"
			+ "      <Hobbies>"
			+ "        <RowId>1-1F3MYTT</RowId>"
			+ "        <Name>Sports &amp; In/Outdoor Activities</Name>"
			+ "        <Value>Sports &amp; In/Outdoor Activities</Value>"
			+ "      </Hobbies>"
			+ "      <Hobbies>"
			+ "        <RowId>1-1F3MYTP</RowId>"
			+ "        <Name>Travel &amp; Holidays</Name>"
			+ "        <Value>Travel &amp; Holidays</Value>"
			+ "      </Hobbies>"
			+ "      <DeviceOwnership>"
			+ "        <RowId>1-1F3MYTM</RowId>"
			+ "        <Name>High Definition TV</Name>"
			+ "        <Value>High Definition TV</Value>"
			+ "      </DeviceOwnership>"
			+ "      <DeviceOwnership>"
			+ "        <RowId>1-3I5C8T3</RowId>"
			+ "        <Name>No Answer Given</Name>"
			+ "        <Value>No Answer Given</Value>"
			+ "      </DeviceOwnership>"
			+ "      <DeviceOwnership>"
			+ "        <RowId>1-1F3MYTK</RowId>"
			+ "        <Name>PC / Laptop</Name>"
			+ "        <Value>PC / Laptop</Value>"
			+ "      </DeviceOwnership>"
			+ "      <DeviceOwnership>"
			+ "        <RowId>1-1F3MYTL</RowId>"
			+ "        <Name>PDA / Smartphone</Name>"
			+ "        <Value>PDA / Smartphone</Value>"
			+ "      </DeviceOwnership>"
			+ "    </ConsumerDemographics>"
			+ "    <ContactList>"
			+ "      <Contact>"
			+ "        <PrimaryContactIndicator>N</PrimaryContactIndicator>"
			+ "        <ContactPrimaryIdType/>"
			+ "        <ContactPrimaryIdNo/>"
			+ "        <ContactID>1-10E33CN</ContactID>"
			+ "        <ContactName>CHUAH SAI LING</ContactName>"
			+ "        <OfficePhone/>"
			+ "        <HomePhone/>"
			+ "        <MobilePhone>0123389899</MobilePhone>"
			+ "        <PortalID/>"
			+ "        <EmailAddress>sl1109@yahoo.com</EmailAddress>"
			+ "        <Designation/>"
			+ "      </Contact>"
			+ "      <Contact>"
			+ "        <PrimaryContactIndicator>N</PrimaryContactIndicator>"
			+ "        <ContactPrimaryIdType/>"
			+ "        <ContactPrimaryIdNo/>"
			+ "        <ContactID>1-3I5C8SV</ContactID>"
			+ "        <ContactName>CHUAH SAI LING</ContactName>"
			+ "        <OfficePhone/>"
			+ "        <HomePhone/>"
			+ "        <MobilePhone>0123389899</MobilePhone>"
			+ "        <PortalID/>"
			+ "        <EmailAddress>sl1109@yahoo.com</EmailAddress>"
			+ "        <Designation/>"
			+ "      </Contact>"
			+ "      <Contact>"
			+ "        <PrimaryContactIndicator>Y</PrimaryContactIndicator>"
			+ "        <ContactPrimaryIdType/>"
			+ "        <ContactPrimaryIdNo/>"
			+ "        <ContactID>1-3J03SQX</ContactID>"
			+ "        <ContactName>CHUAH SAI LING</ContactName>"
			+ "        <OfficePhone/>"
			+ "        <HomePhone/>"
			+ "        <MobilePhone>0123389899</MobilePhone>"
			+ "        <PortalID/>"
			+ "        <EmailAddress>sl1109@yahoo.com</EmailAddress>"
			+ "        <Designation/>"
			+ "      </Contact>"
			+ "      <Contact>"
			+ "        <PrimaryContactIndicator>N</PrimaryContactIndicator>"
			+ "        <ContactPrimaryIdType/>"
			+ "        <ContactPrimaryIdNo/>"
			+ "        <ContactID>1-3I5C8SZ</ContactID>"
			+ "        <ContactName>CHUAH SAI LING</ContactName>"
			+ "        <OfficePhone/>"
			+ "        <HomePhone/>"
			+ "        <MobilePhone>0123389899</MobilePhone>"
			+ "        <PortalID/>"
			+ "        <EmailAddress>sl1109@yahoo.com</EmailAddress>"
			+ "        <Designation/>"
			+ "      </Contact>"
			+ "      <Contact>"
			+ "        <PrimaryContactIndicator>N</PrimaryContactIndicator>"
			+ "        <ContactPrimaryIdType/>"
			+ "        <ContactPrimaryIdNo/>"
			+ "        <ContactID>1-31QUGYN</ContactID>"
			+ "        <ContactName>GOH</ContactName>"
			+ "        <OfficePhone/>"
			+ "        <HomePhone/>"
			+ "        <MobilePhone>0126805386</MobilePhone>"
			+ "        <PortalID/>"
			+ "        <EmailAddress>sl1109@yahoo.com</EmailAddress>"
			+ "        <Designation/>"
			+ "      </Contact>"
			+ "    </ContactList>"
			+ "    <CommitmentPeriodList>"
			+ "      <CommitmentPeriod>"
			+ "        <CommitmentName/>"
			+ "        <CommitmentDuration/>"
			+ "      </CommitmentPeriod>"
			+ "    </CommitmentPeriodList>"
			+ "    <BillingList>"
			+ "      <BillingAccount>"
			+ "        <BillingAddress>"
			+ "          <TMAddressID/>"
			+ "          <AddressType>Landed</AddressType>"
			+ "          <HouseUnitLot>12</HouseUnitLot>"
			+ "          <Postcode>40170</Postcode>"
			+ "          <Floor/>"
			+ "          <BuildingName/>"
			+ "          <StreetType>JALAN</StreetType>"
			+ "          <StreetName>SETIA NUSANTARA U13/22U</StreetName>"
			+ "          <Section>BANDAR ECO-SETIA SEKSYEN U13</Section>"
			+ "          <City>SHAH ALAM</City>"
			+ "          <State>SELANGOR</State>"
			+ "          <Country>MALAYSIA</Country>"
			+ "        </BillingAddress>"
			+ "        <BillingAccountRowID>1-10E4R3Z</BillingAccountRowID>"
			+ "        <BillingAccountNo>1006898603</BillingAccountNo>"
			+ "        <BillingName>CHUAH SAI LING</BillingName>"
			+ "        <BillingProfileRowID>1-10E4RGD</BillingProfileRowID>"
			+ "        <BillAccountStatus>Active</BillAccountStatus>"
			+ "        <BillingCycle>13</BillingCycle>"
			+ "        <BillingSalesPTT>SELANGOR</BillingSalesPTT>"
			+ "        <BillingType>Detail</BillingType>"
			+ "        <HsbaBtuFlag/>"
			+ "      </BillingAccount>"
			+ "      <BillingAccount>"
			+ "        <BillingAccountRowID>1-3O81PIF</BillingAccountRowID>"
			+ "        <BillingAccountNo>1020195168</BillingAccountNo>"
			+ "        <BillingName>CHUAH SAI LING</BillingName>"
			+ "        <BillingProfileRowID>1-3O81PIL</BillingProfileRowID>"
			+ "        <BillAccountStatus>Active</BillAccountStatus>"
			+ "        <BillingAddress>"
			+ "          <AddressType>Landed</AddressType>"
			+ "          <HouseUnitLot>2</HouseUnitLot>"
			+ "          <Postcode>40170</Postcode>"
			+ "          <Floor/>"
			+ "          <BuildingName/>"
			+ "          <StreetType>JALAN</StreetType>"
			+ "          <StreetName>SETIA DUTA U13/21G</StreetName>"
			+ "          <Section>BANDAR ECO-SETIA SEKSYEN U13</Section>"
			+ "          <City>SHAH ALAM</City>"
			+ "          <State>SELANGOR</State>"
			+ "          <Country>MALAYSIA</Country>"
			+ "        </BillingAddress>"
			+ "        <BillingCycle>19</BillingCycle>"
			+ "        <BillingSalesPTT/>"
			+ "        <BillingType>Detail</BillingType>"
			+ "        <HsbaBtuFlag/>"
			+ "      </BillingAccount>"
			+ "    </BillingList>"
			+ "  </Response>"
			+ "</PortalMessage>";
}
